{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "ff44c111",
   "metadata": {},
   "source": [
    "# **Crypto money analytics bot**"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8ee22e8d",
   "metadata": {},
   "source": [
    "### **installing required libraries**"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "feac7975",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from bs4 import BeautifulSoup \n",
    "from selenium import webdriver  # pip install selenium\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from webdriver_manager.chrome import ChromeDriverManager  # pip install webdriver-manager\n",
    "import re"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "ce50e9c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import telebot\n",
    "import requests"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4faf682a",
   "metadata": {
    "tags": []
   },
   "source": [
    "## Developing bot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "95a17015",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-05-14 22:14:10,711 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:10,715 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:13,755 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:13,756 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:16,810 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:16,811 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:19,885 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:19,886 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:22,927 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:22,928 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:25,968 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:25,969 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:29,011 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:29,012 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:32,051 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:32,053 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:35,096 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:35,096 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:38,137 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:38,138 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:41,397 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:41,398 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:44,438 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:44,439 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:47,483 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:47,484 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:50,524 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:50,525 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:53,565 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:53,566 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:56,777 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:56,779 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:14:59,821 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:14:59,822 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n",
      "2024-05-14 22:15:02,864 (__init__.py:1021 MainThread) ERROR - TeleBot: \"Infinity polling exception: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\"\n",
      "2024-05-14 22:15:02,865 (__init__.py:1023 MainThread) ERROR - TeleBot: \"Exception traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1016, in infinity_polling\n",
      "    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1101, in polling\n",
      "    logger.info('Starting your bot with username: [@%s]', self.user.username)\n",
      "                                                          ^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 279, in user\n",
      "    self._user = self.get_me()\n",
      "                 ^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py\", line 1288, in get_me\n",
      "    apihelper.get_me(self.token)\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 198, in get_me\n",
      "    return _make_request(token, method_url)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 164, in _make_request\n",
      "    json_result = _check_result(method_name, result)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\1\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py\", line 191, in _check_result\n",
      "    raise ApiTelegramException(method_name, result, result_json)\n",
      "telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found\n",
      "\"\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mApiTelegramException\u001b[0m                      Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py:1016\u001b[0m, in \u001b[0;36mTeleBot.infinity_polling\u001b[1;34m(self, timeout, skip_pending, long_polling_timeout, logger_level, allowed_updates, restart_on_change, path_to_watch, *args, **kwargs)\u001b[0m\n\u001b[0;32m   1015\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1016\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mpolling(non_stop\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m, timeout\u001b[38;5;241m=\u001b[39mtimeout, long_polling_timeout\u001b[38;5;241m=\u001b[39mlong_polling_timeout,\n\u001b[0;32m   1017\u001b[0m                  logger_level\u001b[38;5;241m=\u001b[39mlogger_level, allowed_updates\u001b[38;5;241m=\u001b[39mallowed_updates, restart_on_change\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m   1018\u001b[0m                  \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m   1019\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py:1101\u001b[0m, in \u001b[0;36mTeleBot.polling\u001b[1;34m(self, non_stop, skip_pending, interval, timeout, long_polling_timeout, logger_level, allowed_updates, none_stop, restart_on_change, path_to_watch)\u001b[0m\n\u001b[0;32m   1099\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_setup_change_detector(path_to_watch)\n\u001b[1;32m-> 1101\u001b[0m logger\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mStarting your bot with username: [@\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m]\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39muser\u001b[38;5;241m.\u001b[39musername)\n\u001b[0;32m   1103\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mthreaded:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py:279\u001b[0m, in \u001b[0;36mTeleBot.user\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    278\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_user:\n\u001b[1;32m--> 279\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_user \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mget_me()\n\u001b[0;32m    280\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_user\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py:1288\u001b[0m, in \u001b[0;36mTeleBot.get_me\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1281\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   1282\u001b[0m \u001b[38;5;124;03mA simple method for testing your bot's authentication token. Requires no parameters.\u001b[39;00m\n\u001b[0;32m   1283\u001b[0m \u001b[38;5;124;03mReturns basic information about the bot in form of a User object.\u001b[39;00m\n\u001b[0;32m   1284\u001b[0m \n\u001b[0;32m   1285\u001b[0m \u001b[38;5;124;03mTelegram documentation: https://core.telegram.org/bots/api#getme\u001b[39;00m\n\u001b[0;32m   1286\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   1287\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m types\u001b[38;5;241m.\u001b[39mUser\u001b[38;5;241m.\u001b[39mde_json(\n\u001b[1;32m-> 1288\u001b[0m     apihelper\u001b[38;5;241m.\u001b[39mget_me(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtoken)\n\u001b[0;32m   1289\u001b[0m )\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py:198\u001b[0m, in \u001b[0;36mget_me\u001b[1;34m(token)\u001b[0m\n\u001b[0;32m    197\u001b[0m method_url \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mr\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mgetMe\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m--> 198\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m _make_request(token, method_url)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py:164\u001b[0m, in \u001b[0;36m_make_request\u001b[1;34m(token, method_name, method, params, files)\u001b[0m\n\u001b[0;32m    162\u001b[0m logger\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe server returned: \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{0}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(result\u001b[38;5;241m.\u001b[39mtext\u001b[38;5;241m.\u001b[39mencode(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mutf8\u001b[39m\u001b[38;5;124m'\u001b[39m)))\n\u001b[1;32m--> 164\u001b[0m json_result \u001b[38;5;241m=\u001b[39m _check_result(method_name, result)\n\u001b[0;32m    165\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m json_result:\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\apihelper.py:191\u001b[0m, in \u001b[0;36m_check_result\u001b[1;34m(method_name, result)\u001b[0m\n\u001b[0;32m    190\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m result_json[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mok\u001b[39m\u001b[38;5;124m'\u001b[39m]:\n\u001b[1;32m--> 191\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ApiTelegramException(method_name, result, result_json)\n\u001b[0;32m    193\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m result_json\n",
      "\u001b[1;31mApiTelegramException\u001b[0m: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[3], line 87\u001b[0m\n\u001b[0;32m     80\u001b[0m                         \u001b[38;5;66;03m#except:          \u001b[39;00m\n\u001b[0;32m     81\u001b[0m                                 \u001b[38;5;66;03m#bot.send_message(message.chat.id, text = 'there is no crypto with this name')  \u001b[39;00m\n\u001b[0;32m     82\u001b[0m \n\u001b[0;32m     83\u001b[0m                     \n\u001b[0;32m     84\u001b[0m     \u001b[38;5;66;03m#time.sleep(300)\u001b[39;00m\n\u001b[0;32m     86\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124m__main__\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[1;32m---> 87\u001b[0m     bot\u001b[38;5;241m.\u001b[39minfinity_polling(none_stop \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\telebot\\__init__.py:1024\u001b[0m, in \u001b[0;36mTeleBot.infinity_polling\u001b[1;34m(self, timeout, skip_pending, long_polling_timeout, logger_level, allowed_updates, restart_on_change, path_to_watch, *args, **kwargs)\u001b[0m\n\u001b[0;32m   1022\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m logger_level \u001b[38;5;129;01mand\u001b[39;00m logger_level \u001b[38;5;241m>\u001b[39m\u001b[38;5;241m=\u001b[39m logging\u001b[38;5;241m.\u001b[39mDEBUG:\n\u001b[0;32m   1023\u001b[0m         logger\u001b[38;5;241m.\u001b[39merror(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mException traceback:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, traceback\u001b[38;5;241m.\u001b[39mformat_exc())\n\u001b[1;32m-> 1024\u001b[0m     time\u001b[38;5;241m.\u001b[39msleep(\u001b[38;5;241m3\u001b[39m)\n\u001b[0;32m   1025\u001b[0m     \u001b[38;5;28;01mcontinue\u001b[39;00m\n\u001b[0;32m   1026\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m logger_level \u001b[38;5;129;01mand\u001b[39;00m logger_level \u001b[38;5;241m>\u001b[39m\u001b[38;5;241m=\u001b[39m logging\u001b[38;5;241m.\u001b[39mINFO:\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "bot = telebot.TeleBot('TOKEN')\n",
    "\n",
    "@bot.message_handler(commands = ['start'])\n",
    "def start(message):\n",
    "    bot.send_message(message.chat.id, 'Hello! It`s new telegram crypto bot. to check does crypto got yout price limit enter /set_data')\n",
    "    \n",
    "         \n",
    "         \n",
    "@bot.message_handler(commands = ['set_data'])\n",
    "def func3(message):\n",
    "    msg = bot.send_message(message.chat.id, text = 'Enter data in format price1/condition1/currency1,price2/condition2/currency2 ..... : ')\n",
    "    bot.register_next_step_handler(msg, Is_got)   \n",
    "\n",
    "\n",
    "@bot.message_handler(commands = ['is_got'])\n",
    "def Is_got(message):\n",
    "    user_text = message.text\n",
    "    do_break = 0 \n",
    "    \n",
    "    global currency_dict\n",
    "    currency_dict = {}\n",
    "    \n",
    "    for n, i in enumerate(user_text.split(',')):\n",
    "        currency_dict[\"currency\" + str(n)]  = 0\n",
    "    \n",
    "    while True:\n",
    "            for n, bc in enumerate(user_text.split(',')):\n",
    "                            df = pd.read_csv(\"bot_file.csv\")\n",
    "                           \n",
    "                            global do_broke\n",
    "                            do_broke = 0\n",
    "                        \n",
    "                            if list(df[\"a\"])[0] == 1:\n",
    "                                do_broke = 1\n",
    "                            b1 = bc.split('/')\n",
    "                            user_price = b1[0]\n",
    "                            ml = b1[1]\n",
    "                            user_currency = b1[2]\n",
    "                        #try:\n",
    "                            with webdriver.Chrome(service=Service(ChromeDriverManager().install())) as driver:  # open chrome\n",
    "                                driver.get('https://www.binance.com/en/price/' + str(user_currency))  # open page\n",
    "                                time.sleep(3)  # time to load webpage\n",
    "                                soup = BeautifulSoup(driver.page_source, 'html.parser') \n",
    "    \n",
    "                            for n, i1 in enumerate(list(soup(\"div\"))):\n",
    "                                if i1.get(\"id\") == \"__APP\":\n",
    "                                    for n1,i in enumerate(list(i1(\"section\"))):\n",
    "                                        if i.get(\"class\") == ['css-2tpvhp']:\n",
    "                                            for a in i('div'):\n",
    "                                                if a.get(\"class\") == [\"css-1ovykgb\"]:\n",
    "                                                    for b in list(a(\"div\")):\n",
    "                                                        if b.get(\"class\") == [\"css-1xmcoai\"]:\n",
    "                                                            for c in b(\"div\"):\n",
    "                                                                if c.get(\"class\") == [\"css-197puc0\"]:\n",
    "                                                                    for d in c(\"div\"):\n",
    "                                                                        if d.get(\"class\") == [\"css-1267ixm\"]:\n",
    "                                                                            for e in d(\"div\"):\n",
    "                                                                                if e.get(\"class\") == [\"css-1bwgsh3\"]:\n",
    "                                                                                    real_price = e    \n",
    "                            \n",
    "        \n",
    "                            real_price = str(real_price)\n",
    "                            real_price = real_price[real_price.index(\"$\") + 1:].replace(\"</div>\", '')\n",
    "                            \n",
    "                            real_price = real_price.replace(\",\", \"\") \n",
    "                            \n",
    "                            if ml == 'less' and float(real_price) <= float(user_price):                                \n",
    "                                bot.send_message(message.chat.id, text = 'The price of ' +  str(user_currency)  + ' got your limit ')\n",
    "                                do_break = do_break + 1\n",
    "\n",
    "                            elif ml == 'more' and float(real_price) >= float(user_price):                                \n",
    "                                bot.send_message(message.chat.id, text = 'The price of ' +  str(user_currency)  + ' got your limit ')\n",
    "                                do_break = do_break + 1\n",
    "\n",
    "                                                   \n",
    "            if do_break == len(user_text.split(',')) or do_broke == 1 :\n",
    "                break\n",
    "                \n",
    "            do_break = 0\n",
    "                        #except:          \n",
    "                                #bot.send_message(message.chat.id, text = 'there is no crypto with this name')  \n",
    "\n",
    "                    \n",
    "    #time.sleep(300)\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    bot.polling(none_stop = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3e27fb4a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "96e81e55-4f1c-46e5-bc19-b417b486c292",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
